config/routes.rb
Rails.application.routes.draw do
 
  root 'students#index'
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :pockets
  resources :payments
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new
    @exam = Exam.new
  end    
  def create #untuk memperoses data baru yang dimasukkan di form new
    exam = Exam.new(resources_params)
    exam.save 
    flash[:notice] = 'Exam has been created'
    redirect_to exams_path
  end   
  def edit #menampilkan data yang sudah disimpan
    @exam = Exam.find(params[:id])
  end  
  def update #melakukan proses ketika user mengedit data
    @exam = Exam.find(params[:id])
    @exam.update(resources_params)
    flash[:notice] = 'Exam has been update'
    redirect_to exam_path(@exam)
  end    
  def destroy #untuk menghapus data
    @exam = Exam.find(params[:id])
    @exam.destroy
    flash[:notice] = 'Exam has been destroy'
    redirect_to exams_path(@exam)
  end  
  def index #menampilkan seluruh data yang ada di database
    @exams = Exam.all
  end    
  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @exam = Exam.find(id)
    # render plain: id
    # render plain: @book.title 
   end
  private   
   def resources_params
    params.required(:exam).permit(:title, :mapel, :duration, :nilai, :aktifnonaktif, :level, :student_id)
  end  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
  end
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  def new
    @pocket = Pocket.new
  end    
  def create #untuk memperoses data baru yang dimasukkan di form new
    pocket = Pocket.new(resources_params)
    pocket.save 
    flash[:notice] = 'Pocket has been created'
    redirect_to pockets_path
  end   
  def edit #menampilkan data yang sudah disimpan
    @pocket = Pocket.find(params[:id])
  end  
  def update #melakukan proses ketika user mengedit data
    @pocket = Pocket.find(params[:id])
    @pocket.update(resources_params)
    flash[:notice] = 'Pocket has been update'
    redirect_to pocket_path(@pocket)
  end    
  def destroy #untuk menghapus data
    @pocket = Pocket.find(params[:id])
    @pocket.destroy
    flash[:notice] = 'Pocket has been destroy'
    redirect_to pockets_path(@pocket)
  end  
  def index #menampilkan seluruh data yang ada di database
    @pockets = Pocket.all
  end    
  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @pocket = Pocket.find(id)
    # render plain: id
    # render plain: @book.title 
   end
  private   
   def resources_params
    params.required(:pocket).permit(:title, :mapel, :teacher_id, :student_id, :date)
  end  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    def new
      @report = Report.new
    end    
    def create #untuk memperoses data baru yang dimasukkan di form new
      report = Report.new(resources_params)
      report.save 
      flash[:notice] = 'Report has been created'
      redirect_to reports_path
    end   
    def edit #menampilkan data yang sudah disimpan
      @report = Report.find(params[:id])
    end  
    def update #melakukan proses ketika user mengedit data
      @report = Report.find(params[:id])
      @report.update(resources_params)
      flash[:notice] = 'Report has been update'
      redirect_to report_path(@report)
    end    
    def destroy #untuk menghapus data
      @report = Report.find(params[:id])
      @report.destroy
      flash[:notice] = 'Report has been destroy'
      redirect_to reports_path(@report)
    end  
    def index #menampilkan seluruh data yang ada di database
      @reports = Report.all
    end    
    def show #menampilkan  sebuah data sectemplateara detail
      id = params[:id]
      @report = Report.find(id)
      # render plain: id
      # render plain: @book.title 
     end
    private   
     def resources_params
      params.required(:report).permit(:title, :mapel, :teacher_id, :student_id, :date)
    end  
  end
  

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end    
  def create #untuk memperoses data baru yang dimasukkan di form new
    student = Student.new(resources_params)
    student.save 
    flash[:notice] = 'Student has been created'
    redirect_to students_path
  end   
  def edit #menampilkan data yang sudah disimpan
    @student = Student.find(params[:id])
  end  
  def update #melakukan proses ketika user mengedit data
    @student = Student.find(params[:id])
    @student.update(resources_params)
    flash[:notice] = 'Student has been update'
    redirect_to student_path(@student)
  end    
  def destroy #untuk menghapus data
    @student = Student.find(params[:id])
    @student.destroy
    flash[:notice] = 'Student has been destroy'
    redirect_to students_path(@student)
  end  
  def index #menampilkan seluruh data yang ada di database
    @students = Student.all
  end    
  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @student = Student.find(id)
    # render plain: id
    # render plain: @book.title 
   end
  private   
   def resources_params
    params.required(:student).permit(:name, :username, :age, :kelas, :address, :city, :NIK)
  end  
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def new
      @teacher = Teacher.new
    end    
    def create #untuk memperoses data baru yang dimasukkan di form new
      teacher = Teacher.new(resources_params)
      teacher.save 
      flash[:notice] = 'Teacher has been created'
      redirect_to teachers_path
    end   
    def edit #menampilkan data yang sudah disimpan
      @teacher = Teacher.find(params[:id])
    end  
    def update #melakukan proses ketika user mengedit data
      @teacher = Teacher.find(params[:id])
      @teacher.update(resources_params)
      flash[:notice] = 'Teacher has been update'
      redirect_to teacher_path(@teacher)
    end    
    def destroy #untuk menghapus data
      @teacher = Teacher.find(params[:id])
      @teacher.destroy
      flash[:notice] = 'Teacher has been destroy'
      redirect_to teachers_path(@teacher)
    end  
    def index #menampilkan seluruh data yang ada di database
      @teachers = Teacher.all
    end    
    def show #menampilkan  sebuah data sectemplateara detail
      id = params[:id]
      @teacher = Teacher.find(id)
      # render plain: id
      # render plain: @book.title 
     end
    private   
     def resources_params
      params.required(:teacher).permit(:NIK, :nama, :age, :kelas, :mapel)
    end  
  end
  
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pocket_helper.rb
module PocketHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<%= form_for(@exam) do |f| %>

    <%= f.label :Title %> </br> 

    <%= f.text_field :title %> </br> 

    <%= f.label :Mapel %> </br> 

    <%= f.text_field :mapel %> </br> 

    <%= f.label :Duration%> </br> 

    <%= f.text_field :duration %> </br>

    <%= f.label :Nilai %> </br> 

    <%= f.text_field :nilai %> </br>

    <%= f.label :Aktifnonaktif %> </br> 

    <%= f.text_field :aktifnonaktif %> </br>

    <%= f.label :Level %> </br> 

    <%= f.text_field :level %> </br>

     <%= f.label :Student_id %> </br> 

    <%= f.text_field :student_id %> </br>

    <%= f.submit "Save" %> 

    <%= link_to 'Back', students_path %> 

    

<% end %>

app/views/exams/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>
<div class="container">

<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>Title</th>

        <th>Mapel</th>

        <th>Duration</th>

        <th>Nilai</th>

        <th>Aktifnonaktif</th>

        <th>Level</th>

        <th>Student_id</th>

        <th>Action</th>

    </tr>

    </thead>

    <tbody>

    <% @exams.each do |exam| %>

    <tr>

        <td><%= exam.title %></td>

        <td><%= exam.mapel %></td>
        
        <td><%= exam.duration %></td>

        <td><%= exam.nilai %></td>

        <td><%= exam.aktifnonaktif %></td>

        <td><%= exam.level %></td>

        <td><%= exam.student_id %></td>

        <td>
        <%= link_to 'Detail', exam_path(exam) ,class:"btn btn-outline-primary"%> 
         <%= link_to 'Edit', edit_exam_path(exam),class:"btn btn-outline-warning" %> 
         <%= link_to 'Delete', exam_path(exam) , method: :delete, data: {confirm: 'Apakah anda yakin?'},class:"btn btn-outline-danger" %>
         </td>

        

    </tr>

    <% end %>

    </tbody>

</table> 
<%= link_to 'New exam', new_exam_path(),class:"btn btn-primary" %>
</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/exams/new.html.erb
<%= form_for(@exam) do |s| %>

    <%= s.label :Title %> </br> 

    <%= s.text_field :title %> </br> 

    <%= s.label :Mapel %> </br> 

    <%= s.text_field :mapel %> </br> 

    <%= s.label :Duration %> </br> 

    <%= s.text_field :duration %> </br>

    <%= s.label :Nilai %> </br> 

    <%= s.text_field :nilai %> </br>

    <%= s.label :Aktifnonaktif %> </br> 

    <%= s.text_field :aktifnonaktif %> </br>

    <%= s.label :Level %> </br> 

    <%= s.text_field :level %> </br>

    <%= s.label :Student_id %> </br> 

    <%= s.text_field :student_id %> </br>

    <%= s.submit "Save" %> 

<% end %>
<%= link_to 'Back', exams_path %> 

app/views/exams/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <div class="card" style="width: 18rem;">
<div class="card-body">
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

Title : <%= @exam.title %> </br>

Mapel : <%= @exam.mapel %> </br>

Duration : <%= @exam.duration %> </br>

Nilai : <%= @exam.nilai %> </br>

Nilai : <%= @exam.aktifnonaktif %> </br>

Level : <%= @exam.level %> </br>

Student ID : <%= @exam.student_id %> </br>


 
</div>
</div>
<%= link_to 'Back', exams_path %> 



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/payments/index.html.erb
<h1>Payments#index</h1>
<p>Find me in app/views/payments/index.html.erb</p>

app/views/pockets/edit.html.erb
<%= form_for(@pocket) do |f| %>

    <%= f.label :Balance %> </br> 

    <%= f.text_field :balance %> </br> 

    <%= f.label :Student_id %> </br> 

    <%= f.text_field :student_id %> </br> 

     <%= f.label :Teacher_id %> </br> 

    <%= f.text_field :teacher_id %> </br>

    <%= f.submit "Save" %> 

    <%= link_to 'Back', pockets_path %> 

    

<% end %>

app/views/pockets/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>
<div class="container">

<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>Balance</th>

        <th>Student_id</th>

        <th>Teacher_id</th>

        <th>Action</th>

    </tr>

  </thead>r

    <tbody>

    <% @pockets.each do |pocket| %> 

    <tr>

        <td><%= pocket.balance %></td>

        <td><%= pocket.student_id %></td>

        <td><%= pocket.teacher_id%></td>


        <td>
        <%= link_to 'Detail', pocket_path(pocket) ,class:"btn btn-outline-primary"%> 
         <%= link_to 'Edit', edit_pocket_path(pocket),class:"btn btn-outline-warning" %> 
         <%= link_to 'Delete', pocket_path(pocket) , method: :delete, data: {confirm: 'Apakah anda yakin?'},class:"btn btn-outline-danger" %>
         </td>

        

    </tr>

    <% end %>

    </tbody>

</table> 
<%= link_to 'New Pocket', new_pocket_path(),class:"btn btn-primary" %>
</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pockets/new.html.erb
<%= form_for(@pocket) do |s| %>

    <%= s.label :Balance %> </br> 

    <%= s.text_field :balance %> </br> 

    <%= s.label :Student_id %> </br> 

    <%= s.text_field :student_id %> </br>

    <%= s.label :Teacher_id %> </br> 

    <%= s.text_field :teacher_id %> </br>

    <%= s.submit "Save" %> 

<% end %>
<%= link_to 'Back', pockets_path %> 

app/views/pockets/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <div class="card" style="width: 18rem;">
<div class="card-body">
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

Balance : <%= @pocket.balance %> </br>

Student ID : <%= @pocket.student_id %> </br>

Teacher ID : <%= @pocket.teacher_id %> </br>
 
</div>
</div>
<%= link_to 'Back', pockets_path %> 



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reports/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>
<div class="container">

<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>Title</th>

        <th>Hasil</th>

        <th>Mapel</th>

        <th>Teacher_id</th>

        <th>Student_id</th>

        <th>Date</th>

        <th>Action</th>

    </tr>

    </thead>

    <tbody>

    <% @reports.each do |report| %>

    <tr>

        <td><%= report.title %></td>

        <td><%= report.hasil %></td>
        
        <td><%= report.mapel %></td>

        <td><%= report.teacher_id %></td>

        <td><%= report.student_id%></td>

        <td><%= report.date%></td>

        <td>
        <%= link_to 'Detail', report_path(report) ,class:"btn btn-outline-primary"%> 
         <%= link_to 'Edit', edit_report_path(report),class:"btn btn-outline-warning" %> 
         <%= link_to 'Delete', report_path(report) , method: :delete, data: {confirm: 'Apakah anda yakin?'},class:"btn btn-outline-danger" %>
         </td>

        

    </tr>

    <% end %>

    </tbody>

</table> 
<%= link_to 'New Report', new_report_path(),class:"btn btn-primary" %>
</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/students/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>
<div class="container">
<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>Name</th>

        <th>Username</th>

        <th>Age</th>

        <th>Kelas</th>

        <th>Address</th>

        <th>City</th>

        <th>NIK<th>

    </tr>

    </thead>

    <tbody>

    <% @students.each do |student| %>

    <tr>

        <td><%= student.name %></td>

        <td><%= student.username %></td>

        <td><%= student.age %></td>

        <td><%= student.kelas %></td>

        <td><%= student.address %></td>

        <td><%= student.city %></td>

        <td><%= student.NIK %></td>

        <td>
        <%= link_to 'Detail', student_path(student) ,class:"btn btn-outline-primary"%> 
         <%= link_to 'Edit', edit_student_path(student),class:"btn btn-outline-warning" %> 
         <%= link_to 'Delete', student_path(student) , method: :delete, data: {confirm: 'Apakah anda yakin?'},class:"btn btn-outline-danger" %>
         </td>

       

        

    </tr>

    <% end %>

    </tbody>

    </table> 
    <%= link_to 'New student', new_student_path() ,class:"btn btn-primary" %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
 

app/views/teachers/index.html.erb
<div class="container">
<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>NIK</th>

        <th>Nama</th>

        <th>Age</th>

        <th>Kelas</th>

        <th>Mapel</th>

        <th>Action</th>

    </tr>

    </thead>

    <tbody>

    <% @teachers.each do |teacher| %>

    <tr>

        <td><%= teacher.NIK %></td>

        <td><%= teacher.nama %></td>

        <td><%= teacher.age %></td>

        <td><%= teacher.kelas %></td>

        <td><%= teacher.mapel %></td>

        <td><%= link_to 'Detail', teacher_path(teacher) %> 
         <%= link_to 'Edit', edit_teacher_path(teacher) %>  
         <%= link_to 'Delete', teacher_path(teacher) , method: :delete, data: {confirm: 'Apakah anda yakin?'} %>
         </td>

        

    </tr>

    <% end %>

    </tbody>

</table>  
<%= link_to 'New Teacher', new_teacher_path(),class:"btn btn-primary" %>
</div>

     

app/views/teachers/show.html.erb
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

NIK : <%= @teacher.NIK %> </br>

Nama : <%= @teacher.nama %> </br>

Age : <%= @teacher.age %> </br>

Kelas : <%= @teacher.kelas %> </br>

Mapel : <%= @teacher.mapel %> </br>

 <%= link_to 'Back', teachers_path %> 
 